### ISSUE TITLE
Unable to post lab schedules on weekends using New-AzLabSchedule

### ISSUE THREAD

**Issue by slape** [Azure/azure-devtestlab#759] opened 2021-04-13 22:56 UTC
When using `New-AzLabSchedule` function I can post schedules for labs on any weekday. 
If I provide a date that is a weekend, the function shows that it was successful, but the schedule doesn't actually post.

When observing the following output, you can see that I have executed `New-AzLabSchedule` for every day from 4/11-4/17.
Each execution runs without an error and shows that it is successful. However, upon examining the schedule, only the weekdays are posted, and the weekend days (sat, sun) are not actually scheduled.

```
[2021-04-13T22:34:39.466Z] OUTPUT: properties        : @{enableState=Enabled; start=4/14/2021 6:00:00 PM; end=4/14/2021 10:30:00 PM; recurrencePattern=; timeZoneId=Eastern Standard Time; startAction=; endAction=; notes=Scheduled with the SalesPoll Scheduler Function.; provisioningState=Succeeded; uniqueIdentifier=901dc15d-0636-4235-99c8-60caab28a37a; latestOperationResult=}
[2021-04-13T22:34:39.466Z] OUTPUT: id                : /subscriptions/ca6fcef7-72ed-41ec-842e-7c543cd74697/resourcegroups/cybersecurity-staging/providers/microsoft.labservices/labaccounts/classroom staging/labs/windows/environmentsettings/default/schedules/default_57653
[2021-04-13T22:34:39.466Z] OUTPUT: name              : Default_57653
[2021-04-13T22:34:39.467Z] OUTPUT: type              : Microsoft.LabServices/labAccounts/labs/environmentSettings/schedules
[2021-04-13T22:34:39.467Z] OUTPUT: location          : eastus
[2021-04-13T22:34:39.467Z] OUTPUT: ResourceGroupName : cybersecurity-staging
[2021-04-13T22:34:39.467Z] OUTPUT: LabAccountName    : classroom staging
[2021-04-13T22:34:39.468Z] OUTPUT: LabName           : windows
[2021-04-13T22:34:39.468Z] OUTPUT: 
[2021-04-13T22:34:39.468Z] OUTPUT: 
[2021-04-13T22:34:39.468Z] Executed 'Functions.Scheduler' (Succeeded, Id=0cb4350d-2874-431e-af9f-98a1acba33f2, Duration=8149ms)
[2021-04-13T22:34:39.551Z] OUTPUT: 
[2021-04-13T22:34:39.551Z] OUTPUT: properties        : @{enableState=Enabled; start=4/17/2021 6:00:00 PM; end=4/17/2021 10:30:00 PM; recurrencePattern=; timeZoneId=Eastern Standard Time; startAction=; endAction=; notes=Scheduled with the SalesPoll Scheduler Function.; provisioningState=Succeeded; uniqueIdentifier=095d4cef-44db-4117-b0f7-94a5c444df5f; latestOperationResult=}
[2021-04-13T22:34:39.551Z] OUTPUT: id                : /subscriptions/ca6fcef7-72ed-41ec-842e-7c543cd74697/resourcegroups/cybersecurity-staging/providers/microsoft.labservices/labaccounts/classroom staging/labs/windows/environmentsettings/default/schedules/default_38096
[2021-04-13T22:34:39.552Z] OUTPUT: name              : Default_38096
[2021-04-13T22:34:39.552Z] OUTPUT: type              : Microsoft.LabServices/labAccounts/labs/environmentSettings/schedules
[2021-04-13T22:34:39.553Z] OUTPUT: location          : eastus
[2021-04-13T22:34:39.553Z] OUTPUT: ResourceGroupName : cybersecurity-staging
[2021-04-13T22:34:39.553Z] OUTPUT: LabAccountName    : classroom staging
[2021-04-13T22:34:39.553Z] OUTPUT: LabName           : windows
[2021-04-13T22:34:39.553Z] OUTPUT: 
[2021-04-13T22:34:39.554Z] OUTPUT: 
[2021-04-13T22:34:39.554Z] Executed 'Functions.Scheduler' (Succeeded, Id=fcff78e3-e1c8-4ad6-8bd2-79110c4f156f, Duration=8233ms)
[2021-04-13T22:34:40.153Z] OUTPUT: 
[2021-04-13T22:34:40.153Z] OUTPUT: properties        : @{enableState=Enabled; start=4/16/2021 6:00:00 PM; end=4/16/2021 10:30:00 PM; recurrencePattern=; timeZoneId=Eastern Standard Time; startAction=; endAction=; notes=Scheduled with the SalesPoll Scheduler Function.; provisioningState=Succeeded; uniqueIdentifier=c13a5f41-44cf-48cf-b9f5-38c29c8e483e; latestOperationResult=}
[2021-04-13T22:34:40.154Z] OUTPUT: id                : /subscriptions/ca6fcef7-72ed-41ec-842e-7c543cd74697/resourcegroups/cybersecurity-staging/providers/microsoft.labservices/labaccounts/classroom staging/labs/windows/environmentsettings/default/schedules/default_74777
[2021-04-13T22:34:40.154Z] OUTPUT: name              : Default_74777
[2021-04-13T22:34:40.155Z] OUTPUT: type              : Microsoft.LabServices/labAccounts/labs/environmentSettings/schedules
[2021-04-13T22:34:40.155Z] OUTPUT: location          : eastus
[2021-04-13T22:34:40.155Z] OUTPUT: ResourceGroupName : cybersecurity-staging
[2021-04-13T22:34:40.155Z] OUTPUT: LabAccountName    : classroom staging
[2021-04-13T22:34:40.156Z] OUTPUT: LabName           : windows
[2021-04-13T22:34:40.156Z] OUTPUT: 
[2021-04-13T22:34:40.156Z] OUTPUT: 
[2021-04-13T22:34:40.156Z] Executed 'Functions.Scheduler' (Succeeded, Id=476455d0-acc5-40a7-b9f9-f2d2a704aaff, Duration=8836ms)
[2021-04-13T22:34:40.175Z] OUTPUT: 
[2021-04-13T22:34:40.176Z] OUTPUT: properties        : @{enableState=Enabled; start=4/15/2021 6:00:00 PM; end=4/15/2021 10:30:00 PM; recurrencePattern=; timeZoneId=Eastern Standard Time; startAction=; endAction=; notes=Scheduled with the SalesPoll Scheduler Function.; provisioningState=Succeeded; uniqueIdentifier=e718c013-affb-4969-82f1-b4ec1ad85a3d; latestOperationResult=}
[2021-04-13T22:34:40.176Z] OUTPUT: id                : /subscriptions/ca6fcef7-72ed-41ec-842e-7c543cd74697/resourcegroups/cybersecurity-staging/providers/microsoft.labservices/labaccounts/classroom staging/labs/windows/environmentsettings/default/schedules/default_88306
[2021-04-13T22:34:40.176Z] OUTPUT: name              : Default_88306
[2021-04-13T22:34:40.176Z] OUTPUT: type              : Microsoft.LabServices/labAccounts/labs/environmentSettings/schedules
[2021-04-13T22:34:40.176Z] OUTPUT: location          : eastus
[2021-04-13T22:34:40.176Z] OUTPUT: ResourceGroupName : cybersecurity-staging
[2021-04-13T22:34:40.177Z] OUTPUT: LabAccountName    : classroom staging
[2021-04-13T22:34:40.177Z] OUTPUT: LabName           : windows
[2021-04-13T22:34:40.177Z] OUTPUT: 
[2021-04-13T22:34:40.177Z] OUTPUT: 
[2021-04-13T22:34:40.177Z] Executed 'Functions.Scheduler' (Succeeded, Id=7b269853-39b3-4d0c-8da3-163d30615846, Duration=8857ms)
[2021-04-13T22:34:40.327Z] OUTPUT: 
[2021-04-13T22:34:40.327Z] OUTPUT: properties        : @{enableState=Enabled; start=4/13/2021 6:00:00 PM; end=4/13/2021 10:30:00 PM; recurrencePattern=; timeZoneId=Eastern Standard Time; startAction=; endAction=; notes=Scheduled with the SalesPoll Scheduler Function.; provisioningState=Succeeded; uniqueIdentifier=d87d101e-1342-4534-8011-e6ec0732705f; latestOperationResult=}
[2021-04-13T22:34:40.328Z] OUTPUT: id                : /subscriptions/ca6fcef7-72ed-41ec-842e-7c543cd74697/resourcegroups/cybersecurity-staging/providers/microsoft.labservices/labaccounts/classroom staging/labs/windows/environmentsettings/default/schedules/default_82881
[2021-04-13T22:34:40.328Z] OUTPUT: name              : Default_82881
[2021-04-13T22:34:40.328Z] OUTPUT: type              : Microsoft.LabServices/labAccounts/labs/environmentSettings/schedules
[2021-04-13T22:34:40.329Z] OUTPUT: location          : eastus
[2021-04-13T22:34:40.329Z] OUTPUT: ResourceGroupName : cybersecurity-staging
[2021-04-13T22:34:40.330Z] OUTPUT: LabAccountName    : classroom staging
[2021-04-13T22:34:40.330Z] OUTPUT: LabName           : windows
[2021-04-13T22:34:40.330Z] OUTPUT: 
[2021-04-13T22:34:40.330Z] OUTPUT: 
[2021-04-13T22:34:40.331Z] Executed 'Functions.Scheduler' (Succeeded, Id=e4d0bbef-225f-49b5-87ff-9d280773493d, Duration=9012ms)
[2021-04-13T22:34:41.716Z] OUTPUT: 
[2021-04-13T22:34:41.716Z] OUTPUT: properties        : @{enableState=Enabled; start=4/11/2021 6:00:00 PM; end=4/11/2021 10:30:00 PM; recurrencePattern=; timeZoneId=Eastern Standard Time; startAction=; endAction=; notes=Scheduled with the SalesPoll Scheduler Function.; provisioningState=Succeeded; uniqueIdentifier=07bc552c-f68a-41a6-9f94-7ce10cf6e1ac; latestOperationResult=}
[2021-04-13T22:34:41.717Z] OUTPUT: id                : /subscriptions/ca6fcef7-72ed-41ec-842e-7c543cd74697/resourcegroups/cybersecurity-staging/providers/microsoft.labservices/labaccounts/classroom staging/labs/windows/environmentsettings/default/schedules/default_59560
[2021-04-13T22:34:41.717Z] OUTPUT: name              : Default_59560
[2021-04-13T22:34:41.717Z] OUTPUT: type              : Microsoft.LabServices/labAccounts/labs/environmentSettings/schedules
[2021-04-13T22:34:41.717Z] OUTPUT: location          : eastus
[2021-04-13T22:34:41.717Z] OUTPUT: ResourceGroupName : cybersecurity-staging
[2021-04-13T22:34:41.718Z] OUTPUT: LabAccountName    : classroom staging
[2021-04-13T22:34:41.718Z] OUTPUT: LabName           : windows
[2021-04-13T22:34:41.718Z] OUTPUT: 
[2021-04-13T22:34:41.718Z] OUTPUT: 
[2021-04-13T22:34:41.718Z] Executed 'Functions.Scheduler' (Succeeded, Id=14e118d9-4b46-4985-8c7b-f37f238a30a3, Duration=10401ms)
[2021-04-13T22:34:42.606Z] OUTPUT: 
[2021-04-13T22:34:42.607Z] OUTPUT: properties        : @{enableState=Enabled; start=4/12/2021 6:00:00 PM; end=4/12/2021 10:30:00 PM; recurrencePattern=; timeZoneId=Eastern Standard Time; startAction=; endAction=; notes=Scheduled with the SalesPoll Scheduler Function.; provisioningState=Succeeded; uniqueIdentifier=28ab6354-3dcf-48b1-9eaf-ac544d773f03; latestOperationResult=}
[2021-04-13T22:34:42.607Z] OUTPUT: id                : /subscriptions/ca6fcef7-72ed-41ec-842e-7c543cd74697/resourcegroups/cybersecurity-staging/providers/microsoft.labservices/labaccounts/classroom staging/labs/windows/environmentsettings/default/schedules/default_24019
[2021-04-13T22:34:42.607Z] OUTPUT: name              : Default_24019
[2021-04-13T22:34:42.607Z] OUTPUT: type              : Microsoft.LabServices/labAccounts/labs/environmentSettings/schedules
[2021-04-13T22:34:42.608Z] OUTPUT: location          : eastus
[2021-04-13T22:34:42.608Z] OUTPUT: ResourceGroupName : cybersecurity-staging
[2021-04-13T22:34:42.608Z] OUTPUT: LabAccountName    : classroom staging
[2021-04-13T22:34:42.608Z] OUTPUT: LabName           : windows
[2021-04-13T22:34:42.609Z] OUTPUT: 
[2021-04-13T22:34:42.609Z] OUTPUT: 
[2021-04-13T22:34:42.609Z] Executed 'Functions.Scheduler' (Succeeded, Id=bfa63350-5788-4dd1-9235-3657f1d1cc85, Duration=11291ms)
```

![Screen Shot 2021-04-13 at 6 53 31 PM](https://user-images.githubusercontent.com/34723698/114630901-8de54e80-9c89-11eb-84a0-a5fb089fd474.png)

**Comment by slape** [comment] 2021-04-14 02:29
Looks like the `$WeekDays` array omits Saturday and Sunday: https://github.com/Azure/azure-devtestlab/blob/master/samples/ClassroomLabs/Modules/Library/Az.LabServices.psm1#L1576
...But that _should_ be only relevant while using the `-Weekly` flag. 

samples/ClassroomLabs/Modules/Library/Az.LabServices.psm1:1576
        [Array] $WeekDays = @('Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'),
        
  Here is the block that forms my params:

```
    $params = @{
        TimeZoneId  = $messageHashTable.time_zone
        FromDate    = $messageHashTable.date
        ToDate      = $messageHashTable.date
        StartTime   = $startTime
        EndTime     = $endTime
        Notes       = $notes
        }
    
    $labObj = Get-ClassLab($messageHashTable)
    #$labSchedule = Get-AzLabSchedule -Lab $labObj

    New-AzLabSchedule -Lab $labObj @params
```

I am not calling `-Weekly` and I am calling the same date for ToDate and FromDate

**Comment by petehauge** [comment] 2021-04-14 17:21
We appreciate the issue report & letting us know - we'll look into getting this fixed.  Thanks!

**Comment by EMaher** [comment] 2021-04-14 17:25
@slape, 

Thanks for reporting this issue.  The default schedules are weekly, so you would need to set the Frequency to 'Daily' in the params when creating the schedule.  

However, when looking at the code, I did notice an issue with Daily schedules, so I will keep this issue open until I fix that.

Thanks,
Elizabeth

**Comment by Peleke** [comment] 2021-04-14 17:28
Turns out the hunch about `-Frequency 'Weekly'` was relevant, though we remain unsure of why. Here's what we've found:
- Schedules set on weekdays (Monday through Friday) work without issue, using the line below.
  - `New-AzLabSchedule -Lab $lab @scheduleParams`
  - ...Where `$lab` is the result of an invocation of `Get-AzLab`, and `@scheduleParams`  includes the start and end dates, as well as start and end times.
- Schedules set on weekends (Saturday and Sunday) do _not_ appear correctly when scheduled with the above function.
- Schedules _do_ appear successfully on weekends if the function is invoked with the `-Frequency` and `-Weekdays` parameters. E.g.:
  - `New-AzLabSchedule -Lab $lab @scheduleParams -Frequency 'Weekly' -WeekDays 'Saturday'`
  - `New-AzLabSchedule -Lab $lab @scheduleParams -Frequency 'Weekly' -WeekDays 'Sunday'`
  - `New-AzLabSchedule -Lab $lab @scheduleParams -Frequency 'Weekly' -WeekDays @('Saturday', 'Sunday')`

Curiously, setting a schedule for a weekend date _without_ the `Frequency` and `WeekDays` parameters still results in
- An apparently successful execution (no errors, and a `Succeeded` state)
- A schedule object, retrievable via `Get-AzLabSchedule`

Thus, it _appears_ to work -- but schedules set on `Saturday` or `Sunday` don't appear in the UI, whereas schedules set for weekdays do.

Below is an example of a schedule "set" on Sunday (`4/11/2021`), but which did _not_ appear on the UI:

```
PS C:\Users\my_username> $schedules[0]

properties        : @{enableState=Enabled; start=4/11/2021 6:00:00 PM; end=4/11/2021 10:30:00 PM; recurrencePattern=;
                    timeZoneId=Eastern Standard Time; startAction=; endAction=; notes=Scheduled with the SalesPoll
                    Scheduler Function.; provisioningState=Succeeded;
                    uniqueIdentifier=46317a85-2bf7-4a1b-a5ce-16ece8d14218; latestOperationResult=}
id                : /subscriptions/[SUBSCRIPTION ID REMOVED]/resourcegroups/cybersecurity-staging/providers/
                    microsoft.labservices/labaccounts/classroom
                    staging/labs/windows/environmentsettings/default/schedules/default_11021
name              : Default_11021
type              : Microsoft.LabServices/labAccounts/labs/environmentSettings/schedules
location          : eastus
ResourceGroupName : cybersecurity-staging
LabAccountName    : classroom staging
LabName           : windows
```

We're unsure if this is a UI issue, or a problem with the backend logic. I.e., it's unclear if the labs would start at the scheduled time, but the schedule simply isn't appearing in the UI, _or_ if the problem is that the schedule is, in fact, not being set, despite a corresponding object being retrievable.

## Potential Source of Issue/Solution Direction
I'm unsure, but suspect this _might_ have to do with the format of the conditional check in the source for `New-AzLabSchedule`. The function first checks if `Frequency` is set to `Weekly`, and, if so, hits the API with the following request parameters:

```
properties = @{
                            enableState       = 'Enabled'
                            start             = $fullStart
                            end               = $fullEnd
                            recurrencePattern = @{
                                frequency = $Frequency
                                weekDays  = $WeekDays
                                interval  = 1
                                until     = $fullUntil
                            }
                            timeZoneId        = $TimeZoneId
                            
                            # Etc...Rest omitted
                        }
```

`recurrencePattern` seems to be the property responding to our addition of the `-Frequency 'Weekly` -WeekDays 'Saturday'` parameters. The `recurrencePattern` property does not appear in the [`else` branch that fires if `Frequency` is either `Daily` or `Once`](https://github.com/Azure/azure-devtestlab/blob/master/samples/ClassroomLabs/Modules/Library/Az.LabServices.psm1#L1630).

Since `Frequency` defaults to `Weekly`, it seems `New-AzLabSchedule -Lab $lab @scheduleParams -WeekDays 'Saturday'` would be equivalent to `New-AzLabSchedule -Lab $lab @scheduleParams -Frequency 'Weekly' -WeekDays 'Saturday'`. This is what lead me to the hunch that the issue might have to do with the logic of the `else` clause, which contains no reference to either `Frequency` or `WeekDays`.

It seems sufficient to include a note on this in the documentation, since `New-AzLabSchedule` works as expected when invoked the correct way. Pointers on how to call it for weekend schedules should work. If someone can confirm the source of the bug, I'd be happy to PR a patch.

**Comment by EMaher** [comment] 2021-04-16 17:07
@Peleke   Thank you for the comments.  The fix has been merged.  I've also updated the readme to show some more examples.

**Comment by RogerBestMsft** [comment] 2021-04-16 17:08
Fix merged.

**Closed by RogerBestMsft** 2021-04-16 17:08 UTC
