### ISSUE TITLE
Exception occurring when using Azure DevTest Labs Create VM Taske

### ISSUE THREAD

**Issue by LukeRH** [Azure/azure-devtestlab#531] opened 2019-07-16 08:58 UTC
Yesterday (15 July 2019) everything was working fine using the "Azure DevTest Labs Create VM" (2.0.36) build task.

Today (16 July 2019) the task is now failing:

##[error]System.TypeLoadException: Could not load type 'Microsoft.IdentityModel.Clients.ActiveDirectory.AdalTrace' from assembly 'Microsoft.IdentityModel.Clients.ActiveDirectory, Version=3.19.4.11002, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.
    at Microsoft.WindowsAzure.Commands.Common.DebugStreamTraceListener.AddAdalTracing(DebugStreamTraceListener listener)
    at Microsoft.Azure.Commands.ResourceManager.Common.AzureRMCmdlet.SetupDebuggingTraces() in d:\workspace\powershell-sign\src\ResourceManager\Common\Commands.ResourceManager.Common\AzureRMCmdlet.cs:line 287
    at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.BeginProcessing() in d:\workspace\powershell-sign\src\Common\Commands.Common\AzurePSCmdlet.cs:line 269
    at Microsoft.Azure.Commands.Profile.AddAzureRMAccountCommand.BeginProcessing() in d:\workspace\powershell-sign\src\ResourceManager\Profile\Commands.Profile\Account\AddAzureRmAccount.cs:line 116
    at System.Management.Automation.Cmdlet.DoBeginProcessing()
    at System.Management.Automation.CommandProcessorBase.DoBegin()
##[error]System.Management.Automation.RuntimeException: There was an error with the service principal used for deployment.

This occurs only on hosted agents. Hosted VS2017 and Hosted 2019 with VS2019 are the two that we have tried and found the problem to manifest on. It may well occur on all Hosted VMs.

When switching to private agents created from an older version of the Hosted VS2017 Packer scripts on GitHub, it works fine.

Please could you look into this.

Thanks
Luke

**Comment by leovms** [comment] 2019-07-16 14:27
The Azure DevOps team had released an update that broke tasks that used the legacy AAD APIs. They have since reverted the changes. It affects custom agents that updated with these changes. Can you please retry it and let us know if it is still broken? Alternatively, trigger an agent update manually and retry.

**Comment by LukeRH** [comment] 2019-07-16 16:05
Thanks for your reply. 

Unfortunately we still see this issue. As its hosted agents we cant manually force an update to the agents. 
Is there anything else we can do or do we have to wait for the pre-provisioned hosted agent pool vm's to refresh automatically?

**Comment by leovms** [comment] 2019-07-16 16:09
The owner of those agents will have to make sure the reverted changes are propagated. The alternative is to update the tasks, which is something we're looking into. Unfortunately, I don't have any timeline to provide. I'll reach out internally and get back to you. Is it possible to switch to another agent for now to unblock you?

**Comment by leovms** [comment] 2019-07-16 16:15
The issue is with the agent package. The responsible team is working to resolve it. They are now aware of the issue. Unfortunately, all I can offer is to update this thread when they indicate full resolution.

**Comment by paulomatiolimosaic** [comment] 2019-07-16 18:38
> The issue is with the agent package. The responsible team is working to resolve it. They are now aware of the issue. Unfortunately, all I can offer is to update this thread when they indicate full resolution.

Do we have any MSFT ticket open about this issue? Can you share it with US? How can we track this issue resolution?

**Comment by leovms** [comment] 2019-07-16 18:43
Yes, there's an internal ticket open that I'm tracking. I'll update the status here, when they indicate resolution.

**Comment by paulomatiolimosaic** [comment] 2019-07-17 12:38
Hey @leovms, do we have any update from MSFT ?

Thanks

**Comment by leovms** [comment] 2019-07-17 12:51
@paulomatiolimosaic, the issue have been marked as mitigated. They have deployed a new agent version. Can you please retry and let me know? There's no clear indication if the hosted environments managed to get update though.

**Comment by sharifAI** [comment] 2019-07-17 13:31
@leovms Unfortunately the issue is not resolved as of yet. Any ideas on when the hosted environments get updated?

**Comment by leovms** [comment] 2019-07-17 13:34
I'm sorry to hear that. I do not know. I've already emailed the team responsible to confirm when the updates happen to those environments. I'm awaiting a response.

**Comment by leovms** [comment] 2019-07-18 14:59
I've received an update this morning. The affected agent hosts have been updated. Can you please retry and let us know if you still observe the issue?

**Comment by juteasl** [comment] 2019-07-18 15:24
This is working again as expected.  Thank you!

**Comment by paulomatiolimosaic** [comment] 2019-07-18 15:28
MSFT recommends to install new agent with this private agent version to resolve this issue. https://vstsagentpackage.azureedge.net/agent/2.154.2/vsts-agent-win-x64-2.154.2.zip

**Comment by leovms** [comment] 2019-07-18 15:29
We're also working to update our tasks to remove that dependency and hopefully prevent being broken again in future. Thanks all for the updates.

**Closed by leovms** 2019-07-18 15:29 UTC

**Comment by DerekSMorin** [comment] 2024-10-04 13:45
I am seeing the same error recently.

We are using the 1.0 version of the task.  I am planning on trying the 3.0 ( preview ) version of the task.

We are seeing it with the delete vm task.

Task 'AzureDevTestLabsDeleteVM' (1.0.7) is using deprecated task execution handler. The task should use the supported task-lib: https://aka.ms/tasklib

2024-10-04T12:27:44.7640461Z ##[error]System.TypeLoadException: Could not load type 'Microsoft.IdentityModel.Clients.ActiveDirectory.AdalTrace' from assembly 'Microsoft.IdentityModel.Clients.ActiveDirectory, Version=3.19.4.11002, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.
2024-10-04T12:27:44.7643219Z    at Microsoft.WindowsAzure.Commands.Common.DebugStreamTraceListener.AddAdalTracing(DebugStreamTraceListener listener)
2024-10-04T12:27:44.7653708Z    at Microsoft.Azure.Commands.ResourceManager.Common.AzureRMCmdlet.SetupDebuggingTraces() in d:\workspace\powershell-sign\src\ResourceManager\Common\Commands.ResourceManager.Common\AzureRMCmdlet.cs:line 287
2024-10-04T12:27:44.7654971Z    at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.BeginProcessing() in d:\workspace\powershell-sign\src\Common\Commands.Common\AzurePSCmdlet.cs:line 269
