### ISSUE TITLE
Issue with creating image when other artifacts have been used

### ISSUE THREAD

**Issue by gregpakes** [Azure/azure-devtestlab#251] opened 2017-06-20 23:56 UTC
I am deploying a VM with a number of artifacts.  I am then trying to create an image of the VM.  When I do that, another artifact is attempted to run which syspreps the VM.  That artifact fails with the error:

> Multiple VMExtensions per handler not supported for OS type 'Windows'. VMExtension 'customScriptArtifact-183362431' with handler 'Microsoft.Compute.CustomScriptExtension' already added or specified in input.

I have read up on this and found the following workaround: 

https://blogs.technet.microsoft.com/meamcs/2016/01/30/run-two-powershell-scripts-on-a-same-vm-through-custom-script-extension-at-different-stage-of-deployment-in-arm/

This article suggests that I run the following command:

```
Remove-AzurermVMCustomScriptExtension -ResourceGroupName $ResourceGroupName -VMName $CustVMname –Name $customscriptname -Force
```

This is fine and I can work this into my workflow, but my question is:

**How do I know what the $customscriptname parameter should be to pass into the command above?**

I am using this in the context of the ImageFactory, so it's not just a case of manually looking up the extension that was used and then removing it.  It needs to be automatable.  In this case, the only extension applied to the VM is named: WinRMCustomScriptExtension

**Comment by gregpakes** [comment] 2017-06-23 06:00
This is a real blocker now.  Our ImageFactory is no longer working.

**Comment by drwill-ms** [comment] 2017-06-23 21:32
Hi Greg - Is this likely to be fixed by the PR you recently submitted?

**Comment by gregpakes** [comment] 2017-06-25 21:19
@drwill-ms 

No I am still blocked by this.  I'm trying to resolve it, and only have a nasty hack at the moment.

**Comment by gregpakes** [comment] 2017-07-18 06:56
I am totally blocked by this now.

When I try to apply the sysprep artifact, I get the following error:

Multiple VMExtensions per handler not supported for OS type 'Windows'. VMExtension 'customScriptArtifact-183362431' with handler 'Microsoft.Compute.CustomScriptExtension' already added or specified in input.

**Comment by jaymarf** [comment] 2017-07-18 19:07
Hi Greg- I am working on a repro for your issue right now, as far as your initial question you should be able to get the name from within the virtual machine.

**Comment by gregpakes** [comment] 2017-07-18 21:57
@jaymarf 

Thanks - I'll try to run through my scenario.

I think the issue is due to the fact I'm using the **Azure File Copy** task in VSTS.  This task enabled WinRm automatically and it achieves that through a custom script extension.

Logs from VSTS

```
2017-07-18T06:18:18.2209587Z ##[debug]Enabling winrm for virtual machine iSAMS-Img-1049
2017-07-18T06:18:18.2365587Z ##[debug]Adding custom script extension 'WinRMCustomScriptExtension' for virtual machine 'Img-1049'
```

I also think the sysprep task uses the WinRMCustomScriptExtension, so when it tries to apply, it fails.

I am using Windows 2016.  I am applying the sysprep artifact through powershell

**Comment by jaymarf** [comment] 2017-07-20 17:35
This sounds like your problem, I will reach out to the team that owns the Azure File Copy task and talk to them about cleaning up their custom script extension after it has completed running.  You can try running the powershell command that removes the custom script extension from the machine.

**Comment by gregpakes** [comment] 2017-07-21 00:30
@jaymarf 

I have looked at the source of the Azure File Copy task and it looks like they are already removing the extension:

**Comment by tanmayeekamath** [comment] 2019-03-22 18:12
We will be closing this issue. Please reopen if you are still seeing this error.

**Comment by adstep** [comment] 2019-03-30 06:58
I am still seeing this error.

**Comment by leovms** [comment] 2019-04-01 23:43
Let me re-open the issue. We'll investigate further.

**Comment by leovms** [comment] 2019-04-09 20:16
@adstep, can you please provide steps to repro? We sysprep from Azure Portal. Are you using scripts to do this? If so, can you please share so we can troubleshoot further?

**Comment by leovms** [comment] 2019-04-16 20:55
@adstep, closing this issue due to inactivity. If you wish to re-open the issue, please do so and provide the required steps to reproduce.

**Closed by leovms** 2019-04-16 20:55 UTC
