### ISSUE TITLE
Not able to access hub Url.

### ISSUE THREAD

**Issue by vikassahnimca** [Azure/azure-devtestlab#372] opened 2018-04-24 18:07 UTC
I have successfully setup selenium grid on public Azure(Trial version) using one Node as VM machine.

Hub Machine IP Address allocated as **52.170.187.175** and or FQDN as **seleniumhub375352.eastus.cloudapp.azure.com**

When i am trying to access below URL in Internet explorer on local machine they are working and showing me Grid Console. Which shows Selenium Grid is setup correctly.
http://52.170.187.175:4444/grid/console
http://seleniumhub375352.eastus.cloudapp.azure.com:4444/grid/console

But when i am using below URL in my automation scripts it is not working. and giving me error 
**Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure.**

http://52.170.187.175:4444/wd/hub
OR
http://seleniumhub375352.eastus.cloudapp.azure.com:4444/wd/hub

**Sample Code Script which i written is as below.**
package com.recoveryfacts.zTest;

import org.openqa.selenium.Platform;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import java.net.MalformedURLException;
import java.net.URL;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.testng.Assert;
import org.testng.annotations.AfterTest;
import org.testng.annotations.BeforeTest;
import org.testng.annotations.Test;

public class SeleniumHub9 {
	WebDriver Driver;
	String baseurl, nodeurl;

	@BeforeTest
	public void setup() throws MalformedURLException {
		baseurl = "http://newtours.demoaut.com/";
		nodeurl = "http://seleniumhub375352.eastus.cloudapp.azure.com:4444/wd/hub";
		DesiredCapabilities caps = DesiredCapabilities.internetExplorer();
		caps.setBrowserName("iexplore");
		caps.setPlatform(Platform.WIN8);
		Driver = new RemoteWebDriver(new URL(nodeurl),  caps);
	}
	@AfterTest
	public void afterTest() {
		Driver.quit();
	}
	@Test
	public void simpleTest() throws Exception {
		System.out.println("Test 9");
		System.out.println(baseurl);
		Driver.get(baseurl);
		System.out.println(Driver.getTitle());
		Assert.assertEquals("Welcome: Mercury Tours", Driver.getTitle());
	}
}

Can you please help me to resolve this issue. Is their any step i am missing.

**Comment by drwill-ms** [comment] 2018-04-25 15:13
Hi -

I'm not clear this issue is related to DevTest Labs. I realize you might have used DTL to deploy a VM, but once it is deployed and you are using the VM it is unlikely an issue the DTL team can address.

Regards,
David

**Comment by vikassahnimca** [comment] 2018-04-25 16:08
Yes i deployed VM using DTL. from below Link.
https://github.com/Azure/azure-devtestlab/tree/master/Samples/201-dtl-create-lab-with-seleniumgrid

As per README.md it is mentioned as below.
Q. I want to run tests on my grid, how do I get the hub Url?
A. You can get the hub Url from the output field after clicking on the notification for successful deployment of the template. If you missed this then you can construct the url yourself. All you have to do is get the ipaddress/fqdn of the hub VM from the DevTest Lab instance you just created and replace it in this pattern - http://{ipaddress or fqdn}:4444/wd/hub

With this reference my Hub URls are
http://52.170.187.175:4444/wd/hub
OR
http://seleniumhub375352.eastus.cloudapp.azure.com:4444/wd/hub

But from my Automation script it is not working.

How i can reach out to DTL team. Or can anyone from DTL help me out.

**Comment by drwill-ms** [comment] 2018-04-25 16:49
You have the DTL team. I'm a team member. :)

Please note this ARM template sample was submitted by a member of the community, so we're not exactly experts on selenium or this sample, and it will take some time for us to ramp up.

Can you tell me a little more about your lab's vnet configuration? Have you customized it at all? It will default to a shared IP address, meaning your RDP port will be mapped from an external-facing port chosen at random, to 3389 on the VM. If you use this configuration, the resulting VM will have a fully-qualified domain name. You'll find this value in the VM blade, in the Essentials section at the top.

This means that you will not have an open HTTP port to the Internet, if that is what you need for selenium to work. If you need that, you'll want to select a public IP address instead when creating the VM.

Can you tell me more about the automation script? Does it run locally on that VM and access resources only inside that VM? Is there any inbound network traffic to the VM from an external client?

Regards,
David

**Comment by drwill-ms** [comment] 2018-04-25 22:08
I've spent a bit more time looking through the ARM template, so I understand it better. It creates a lab, creates a VM as the Selenium hub with a public IP address, and then creates N number of specified nodes with shared IP addresses.

Assuming the nodes are all making requests to the hub on port 4444, which is open on the hub because it is was provisioned with a public IP address, the communication there should be fine.

I agree, based on the ReadMe, your Hub URI should be http://seleniumhub375352.eastus.cloudapp.azure.com:4444/wd/hub. Also, hitting that URL, some json comes back, so the server is responding.

So as far as I can tell, with respect to the work DTL did to deploy the VMs and run the artifact install scripts, everything looks correctly configured. As far as the test scripts you have that you have to run, I don't know about that and I'm at a loss.

**Comment by javierfigueroa** [comment] 2018-05-17 13:45
I'm having the same issue.  Deployment succeeds but when I try to access the output url, I don't get a response.

I'm able to RDP into the hub machine and go to the grid url at http://localhost:4444/grid/console but it doesn't seem to be accessible from the outside.  The windows machine also shows the firewall has port 4444 open.

**Comment by junhuac** [comment] 2018-08-28 23:55
I have identified the root cause of this issue. DevTestLab artifact "Selenium-grid node" sets up a firewall rule SeleniumGridNode, which only allows inbound/outbound traffic from local port 5555. The solution is to config Node Port 5555 in DefaultNodeWebDriver.json.

Artifact source code:
https://github.com/Azure/azure-devtestlab/blob/master/Artifacts/windows-seleniumgrid-node/GridDeployer.ps1

Line 147:

        if(-Not $firewallRule) 
        {
            #Enable Firewall access for the node
            New-NetFirewallRule -displayname SeleniumGridNode -direction inbound -action allow -protocol tcp -remotePort Any -localport 5555 | out-null
            New-NetFirewallRule -displayname SeleniumGridNode -direction outbound -action allow -protocol tcp -remotePort Any -localport 5555 | out-null
            Write-Host -Object "Added Firewall exception for port 5555."
        }

**Comment by leovms** [comment] 2019-04-09 20:07
@ShreyasRmsft, I was wondering if you can comment on this issue. As you seem to be the original author of this artifact, you may have more context on the proposed fix.

**Comment by ShreyasRmsft** [comment] 2019-04-10 05:29
Port 5555 was for the nodes and port 4444 was for the hub if I remember correctly (This was authored quite some time ago)

https://github.com/Azure/azure-devtestlab/blob/2a8fb218bce0eb7188faaaf0ac8df033d06c9e8c/Artifacts/windows-seleniumgrid-node/GridDeployer.ps1#L114-L130

@vikassahnimca do you have the hub and the node on the same machine?

**Comment by ShreyasRmsft** [comment] 2019-04-10 10:32
@junhuac depending on whether the vm is acting as a hub or node the script opens up the appropriate port (4444 or 5555). I think we deemed having node and hub on the same machine as a non-scenario at the time.

**Comment by leovms** [comment] 2019-04-16 20:58
@junhuac, closing this issue. If you are not configuring the node and hub on the same machine, a scenario that looks not to be supported, feel free to re-open this issue.

**Closed by leovms** 2019-04-16 20:58 UTC
