### ISSUE TITLE
Azure DTL - The selected virtual machine does not support creating a custom image.

### ISSUE THREAD

**Issue by tarunaroraonline** [Azure/azure-devtestlab#269] opened 2017-08-01 13:08 UTC
I am using a custom template to provision a VM with data disk in dev test lab. When i browse to the machine in DTL and click `Create Custom Image` from the blade, it shows me the following information message...

`The selected virtual machine does not support creating a custom image.`

![image](https://user-images.githubusercontent.com/10263817/28826658-c6f7dc06-76c2-11e7-86ee-33877de28748.png)

Do machines creatd from custom images not support custom image functionality?

**Comment by leovms** [comment] 2017-08-01 16:14
Can you elaborate on the scenario? Are you saying you created an Environment with a VM in it using your own ARM template? Any chance you can share the script with me, without any sensitive information, to help troubleshoot?

**Comment by tarunaroraonline** [comment] 2017-08-01 17:19
Leo take a simple custom template that provisions a network card, a data disk for a virtual machine using the Visual Studio Marketplace image. When you now try to create a custom image or formula u get the same message. If you are stuck I can share my template with you, if u have access to live site I can share the subscription and lab details to help investigate this.

**Comment by leovms** [comment] 2017-08-01 17:45
Thank you. I wanted to ensure this was indeed a BYOA scenario. Unfortunately, in a BYOA scenario we do not support some lab features, like creating custom images, by design.

**Comment by tarunaroraonline** [comment] 2017-08-01 17:55
Leo I am using a data disk. Does the lab support creating a snap shot of the data disk and adding that to the custom image library? I know that the service runner gets certain elevated permission when provisioning in the lab, does this also include permissions on data disk? I ask because I am in an enterprise setup with full access to the Dev Test lab resource group but since each new VM gets provisioned in its own new resource group without the runner delegating more permissions it gets hard to use in the enterprise.

**Comment by tarunaroraonline** [comment] 2017-08-01 17:57
Just wanted to acknowledge that I understand this is by design but I see this as a very big limitation. Do you have this on the backlog? When is this forecasted for?

**Comment by leovms** [comment] 2017-08-01 21:47
I'm trying to understand the scenario better. Is there a reason you are not creating the custom image using the normal DTL flow (i.e. not using BYOA)? If you create a lab VM and add a data disk, you can then create a custom image, which will include the data disk, as long as the custom image is generalized.

**Comment by tarunaroraonline** [comment] 2017-08-02 08:01
The simple single vm solution doesn't support is profile specification. Which is required if you want to set up an Internet proxy when the vm is being provisioned. This is a pre-requiste to be able to run the extensions such as download and execute powershell, bgInfo and Domain Join. The simple CM doesn't support this scenario and BYOT doesn't support custom image and formula creation, this use case really needs to be supported in my opinion.

**Comment by ajay-arora** [comment] 2017-08-02 17:33
Tarun, can you setup a call to do this faster. Please send me or Leo a meeting invite.
Meanwhile, if you want to create a custom image from a VM that you created via BYOA, you can follow this approach.
1. Create the VM in Lab via BYOA flow.
2. Apply sysprep artifact on the VM so that the machine is generalized.
3. Once the VM shutsdown, locate its backing VHD from the Compute VM blade Disks blade. If the VM is Managed, you will need to export the disk into a VHD.
4. Once you have the VHD, you can import it into a Lab and create a custom image.

This approach will not include any data disks in the custom image. However if you create a custom image from a VM created in the regular flow (non BYOA), and if its generalized, then the data disks get baked into the custom image.

**Comment by tarunaroraonline** [comment] 2017-08-03 21:27
@ajay-arora what's ur email address? What time zone are you in?

**Comment by ajay-arora** [comment] 2017-08-14 22:35
ajaroraatmicrosoftdotcom. I am in PST.

**Comment by tanmayeekamath** [comment] 2019-03-22 18:13
We will be closing this issue. Please reopen if you are still seeing this error.

**Closed by tanmayeekamath** 2019-03-22 18:13 UTC
